name: CI Pipeline

on:
  push:
    branches:
      - main  # Run the pipeline on every push to the 'main' branch
  pull_request:
    branches:
      - main  # Run the pipeline when a pull request targets the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu machine

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js (if you're using Node.js)

    - name: Install dependencies
      run: npm install  # Install dependencies (you can adjust this for other languages)

    - name: Run tests
      run: npm test  # Run tests (adjust for your testing framework)

    - name: Build the project
      run: npm run build  # Build your project (adjust as needed)


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
